
version: 2.1

orbs:

  python: circleci/python@1.5.0


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command: pytest
workflows:
  sample: 
    jobs:
      - build-and-test
