
version: 2.1

orbs:
  python: circleci/python@1.5.0
  
jobs:
  build-and-test:
    docker:
      - image: theophilesers/p13:version1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}      
      - run:
          command: pip install -r LettingsOC/requirements.txt
          name: Install Deps
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Run tests
          command: pytest LettingsOC
workflows:
  sample: 
    jobs:
      - build-and-test
