version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
    
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8


workflows:
  my-workflow:
    jobs:
      - test-and-lint
