
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@0.0.10
  
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: theophile

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}      
      - run:
          command: pip install -r LettingsOC/requirements.txt
          name: Install Deps
  
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "LettingsOC/requirements.txt" }}

      - run:
          name: Run tests
          command: pytest LettingsOC
workflows:
  sample: 
    jobs:
      - build-and-test
  heroku_deploy:
    working_directory: ~/LettingsOC/
    jobs:
      - heroku/deploy-via-git
