
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@0.0.10
  
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: theophile

    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install Deps
      - run:
          name: Run migrations
          command: |
            . venv/bin/activate
            python manage.py migrate --skip-checks
      - run:
          name: Run tests
          command: pytest
workflows:
  sample: 
    jobs:
      - build-and-test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
