
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@0.0.10


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: theophile

    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install Deps
      - run:
          name: Run makemigrations
          command: python manage.py makemigrations 
      - run:
          name: Run MIGRATE
          command: python manage.py migrate 
      - run:
          name: Run loaddata from Json
          command: python manage.py loaddata datadump.json
      - run:
          name: Run tests
          command: pytest
      
      - setup_remote_docker  
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t theosers/circleci-tutorial:v1 .
          
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
              - build-and-test
