version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lettings
      - POSTGRES_USER=theo
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=lettingsgo
      - POSTGRES_USER=theo
      - POSTGRES_PASSWORD=123456
    depends_on:
      - db